-- Knowledge base: URL slugs and full-text search.
--
-- Slugs are generated by triggers rather than in application code, for the same
-- reason workspaces.inbound_token is a column DEFAULT: there must be no insert
-- path that can produce a row without one. The public KB routes resolve rows by
-- slug alone, so a row with no slug is an unreachable row.

-- ---------------------------------------------------------------------------
-- slugify
-- ---------------------------------------------------------------------------
-- Immutable so it is usable inside generated columns and index expressions.
-- `unaccent` is deliberately not used: it is not immutable (its dictionary is
-- mutable state), which would disqualify it from both. Non-ASCII letters
-- therefore collapse away, and the callers below supply a fallback for a title
-- made up entirely of them.

create or replace function private.slugify(p_input text)
returns text
language sql
immutable
set search_path = ''
as $$
  select nullif(
    btrim(
      regexp_replace(
        regexp_replace(lower(coalesce(p_input, '')), '[^a-z0-9]+', '-', 'g'),
        '(^-+)|(-+$)', '', 'g'
      ),
      '-'
    ),
    ''
  )
$$;

revoke all on function private.slugify(text) from public;
grant execute on function private.slugify(text) to authenticated, service_role;

-- ---------------------------------------------------------------------------
-- workspaces.slug
-- ---------------------------------------------------------------------------

alter table public.workspaces add column slug text;

-- SECURITY DEFINER because the collision check has to see every workspace, not
-- the one row the calling user's RLS policy exposes. The unique constraint
-- below is the real guarantee; this loop only picks a first candidate, so a
-- concurrent insert can still lose the race and raise 23505.
create or replace function private.set_workspace_slug()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_base text;
  v_candidate text;
  v_suffix int := 1;
begin
  -- Derived on insert and never regenerated on rename: the slug is the public
  -- KB URL, and silently breaking every inbound link on a rename is worse than
  -- a slug that no longer matches the display name.
  --
  -- Leaves room for a hyphen and a suffix inside a sane URL length.
  v_base := left(coalesce(private.slugify(new.name), 'workspace'), 80);
  v_candidate := v_base;

  while exists (
    select 1 from public.workspaces
    where slug = v_candidate and id is distinct from new.id
  ) loop
    v_suffix := v_suffix + 1;
    v_candidate := v_base || '-' || v_suffix;
  end loop;

  new.slug := v_candidate;
  return new;
end;
$$;

create trigger workspaces_set_slug
  before insert on public.workspaces
  for each row execute function private.set_workspace_slug();

-- Backfill: existing workspaces predate the trigger. Row-at-a-time so each
-- generated slug is visible to the next row's collision check.
do $$
declare
  r record;
  v_base text;
  v_candidate text;
  v_suffix int;
begin
  for r in select id, name from public.workspaces where slug is null order by created_at loop
    v_base := left(coalesce(private.slugify(r.name), 'workspace'), 80);
    v_candidate := v_base;
    v_suffix := 1;
    while exists (select 1 from public.workspaces where slug = v_candidate) loop
      v_suffix := v_suffix + 1;
      v_candidate := v_base || '-' || v_suffix;
    end loop;
    update public.workspaces set slug = v_candidate where id = r.id;
  end loop;
end;
$$;

alter table public.workspaces alter column slug set not null;
-- The DEFAULT is a placeholder the trigger above always overwrites. It exists
-- so the column can be NOT NULL without every caller — and every generated
-- Insert type — having to supply a slug it has no business choosing. Slug
-- derivation stays in exactly one place. Set after the backfill so existing
-- rows are not silently filled with it.
alter table public.workspaces alter column slug set default 'workspace';
alter table public.workspaces add constraint workspaces_slug_key unique (slug);
alter table public.workspaces
  add constraint workspaces_slug_format
  check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$');

-- ---------------------------------------------------------------------------
-- kb_articles.slug
-- ---------------------------------------------------------------------------

alter table public.kb_articles add column slug text;

create or replace function private.set_kb_article_slug()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_base text;
  v_candidate text;
  v_suffix int := 1;
begin
  -- Derived on insert, regenerated while the article is still a draft, frozen
  -- once it has been published: a published slug is a live URL, and retitling
  -- should not 404 every link to it. To change a published article's URL,
  -- unpublish it, retitle, and publish again.
  if tg_op = 'UPDATE' and (new.title = old.title or old.published) then
    new.slug := old.slug;
    return new;
  end if;

  v_base := left(coalesce(private.slugify(new.title), 'article'), 80);
  v_candidate := v_base;

  while exists (
    select 1 from public.kb_articles
    where workspace_id = new.workspace_id
      and slug = v_candidate
      and id is distinct from new.id
  ) loop
    v_suffix := v_suffix + 1;
    v_candidate := v_base || '-' || v_suffix;
  end loop;

  new.slug := v_candidate;
  return new;
end;
$$;

create trigger kb_articles_set_slug
  before insert or update on public.kb_articles
  for each row execute function private.set_kb_article_slug();

do $$
declare
  r record;
  v_base text;
  v_candidate text;
  v_suffix int;
begin
  for r in select id, workspace_id, title from public.kb_articles where slug is null order by created_at loop
    v_base := left(coalesce(private.slugify(r.title), 'article'), 80);
    v_candidate := v_base;
    v_suffix := 1;
    while exists (
      select 1 from public.kb_articles where workspace_id = r.workspace_id and slug = v_candidate
    ) loop
      v_suffix := v_suffix + 1;
      v_candidate := v_base || '-' || v_suffix;
    end loop;
    update public.kb_articles set slug = v_candidate where id = r.id;
  end loop;
end;
$$;

alter table public.kb_articles alter column slug set not null;
-- Placeholder default, as on workspaces.slug above.
alter table public.kb_articles alter column slug set default 'article';
alter table public.kb_articles
  add constraint kb_articles_workspace_slug_key unique (workspace_id, slug);

-- ---------------------------------------------------------------------------
-- Full-text search
-- ---------------------------------------------------------------------------
-- The body is TipTap HTML, so tags are stripped before indexing or `div` and
-- `strong` would be searchable terms. The regexp is immutable, which is what
-- lets the whole expression live in a stored generated column instead of a
-- trigger that could drift out of sync with the rows.
--
-- Title is weighted A and body B, so a title hit outranks a passing mention
-- halfway down a long article.

alter table public.kb_articles
  add column search_vector tsvector
  generated always as (
    setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
    setweight(
      to_tsvector('english', regexp_replace(coalesce(body, ''), '<[^>]*>', ' ', 'g')),
      'B'
    )
  ) stored;

create index kb_articles_search_idx on public.kb_articles using gin (search_vector);

-- Supports the public KB listing and the widget suggest route, both of which
-- narrow on (workspace_id, published) before ranking.
create index kb_articles_published_idx
  on public.kb_articles (workspace_id, published, updated_at desc);
